### PR TITLE
Bug 1168849 - Bookmark badge

### PR DESCRIPTION
**Pull request by wesj**
This adds support for badging the right and left side of the description, and shows a star for bookmarked pages.

### CODE REVIEW

**Comment by rnewman** [comment]
What happens to the right and left images when running in RTL locales?

If we never use the left image (yet), perhaps comment that out to avoid allocating an extra `UIImageView` per row?

Otherwise, looks good modulo comments.

**Comment by rnewman** [comment]
lttm

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 12 minutes and 57 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by st3fan** [comment]
Moving this past v1.1

**Pull request closed without merging**
