### PR TITLE
UX Polish: Added transparency to home panels, fixed some spacing with search suggestions

### PR DESCRIPTION
**Pull request by darrinhenein**
Mostly visual, made suggestion hit targets bigger as well.

r? @st3fan @wesj @thebnich

### CODE REVIEW

**Comment by darrinhenein** [comment]
Thanks @dusek! Is there a way to set a view as not-accessible but still visible? The idea of this patch is to keep the webview visible behind the panels, so the user understands the context of the panels and that the page is still there (this will become clear once you try a build). Any suggestions on how this could work?

**Comment by dusek** [comment]
@darrinhenein Yes, you can set [`accessibilityElementsHidden`](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIAccessibility_Protocol/index.html#//apple_ref/occ/instp/NSObject/accessibilityElementsHidden) to true (this is exactly for cases where something is not `hidden` and is part of view hierarchy, but it is visually clear for the user it should not be interacted with and it is not even possible to interact with it, so it should be hidden from accessibility). Also don't forget to pair it with setting it again to `false` after stopping showing the home panel :-).

**Comment by dusek** [comment]
@darrinhenein Also transparency should not be used if the user enabled "Reduce Transparency" (checkable with [`UIAccessibilityIsReduceTransparencyEnabled`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIAccessibilityIsReduceTransparencyEnabled)), but that is true probably only in cases where the transparency results in reduction of contrast of content that is being primarily presented (transparent backgrounds usually reduce contrast between themselves and the presented content like text for which they act as a background), so it is up to your consideration if this is the case.

If you are interested in the practical examples of situations of adjusting visual aspects of UI to visual accessibility settings like transparency for this PR and also your future work, I would recommend looking at WWDC 2014 session video "Accessibility on iOS", the Visual Accommodations part (running from 09:40 to 17:00 - i.e. just 7 minutes :-)).

**Comment by darrinhenein** [comment]
I've added the `accessibilityElementsHidden` toggle, let's do the blur/transparency checks in a follow-up.

**Comment by dusek** [comment]
For the record, just tried with and without 43bc010 and confirm 43bc010 really does save accessibility :-) (without it, VoiceOver browses elements from home panel mixed with elements of the hidden webview; with the commit, everything behaves fine – only elements from the home panel are browsed).

**Comment by darrinhenein** [comment]
Great, thanks @dusek! I don't have much experience (shamefully) with the accessibility APIs so really appreciate your help :)

**Comment by dusek** [comment]
My pleasure. Btw. looked at the translucency effect, if the only translucency effect is the home panel bar (where the 5 buttons for switching the panels are), then I don't think it requires removing the transparency when the user has reduce transparency accessibility setting set – the transparency actually appears very slight to me and does not endanger contrast of the buttons against any color of the underlying webpage I tried (I tried black and red).

**Pull request merged**
