### PR TITLE
Bug 1124828 - "Bold Text" accessibility setting not respected

### PR DESCRIPTION
**Pull request by dusek**
I will probably tweak the boldness of some elements in a future commit,
but this is to get started.

### CODE REVIEW

**Comment by thebnich** [comment]
Hey @dusek, thanks for the pull request! Unfortunately, it looks like something has landed since you opened this that causes a number of conflicts in these files. Would you mind rebasing this on the latest master?

**Comment by dusek** [comment]
@thebnich will do, hopefully this evening

**Comment by dusek** [comment]
@thebnich I rebased and fixed all the conflicts and force-pushed, so *right now* it will merge without conflicts :-)

**Comment by thebnich** [comment]
Thanks! Merged 60e5dda.

**Pull request closed without merging**
