### PR TITLE
Bug 1131281 - Bookmarks sqlite tables

### PR DESCRIPTION
**Pull request by wesj**
This implements a local datastore for bookmarks in sqlite. It doesn't support folders or positions yet, because I wanted to get something working with the existing code before I started extending it.

### CODE REVIEW

**Comment by rnewman** [comment]
Please use `Bytes.generateGUID()` instead of `NSUUID().UUID`.

**Comment by rnewman** [comment]
This looks good to me. Please run this past @ncalexan; I recall he was doing some profile-related work that might intersect with this.

**Comment by wesj** [comment]
I had to move Bytes.generateGUID to use it. I'm not sure if you'll like that or not. Easy to move back!

**Comment by rnewman** [comment]
Yeah, generateGUID is super fundamental, so it should be in our earliest utils-ey place.

**Pull request merged**
