### PR TITLE
Bug 1233277 - Pre-land strings for Bug 1232810, confirmation of delete of non-empty folders.

### PR DESCRIPTION
**Pull request by rnewman**

### CODE REVIEW

**Comment by st3fan** [comment]
I'm going to have a better patch for this.

**Comment by rnewman** [comment]
Landed in #1369.

**Comment by rnewman** [comment]
The first commit did not land. If it doesn't, someone needs to do the work in January to prevent bookmark folders from being deleted, because I don't have time to.

The relevant commit is hanging out in #1385.

**Comment by rnewman** [comment]
I landed this commit:

a1cf994

**Pull request closed without merging**
