### PR TITLE
Bugs 1272007, 1272008, 1272234, and 1272261 - Fixed Login and Touch ID bugs

### PR DESCRIPTION
**Pull request by tylerlacroix**

### CODE REVIEW

**Comment by sleroux** [comment]
I tried running some of the bug cases on my device but every time I lock the device the app crashes behind the device's passcode lock screen. Were you seeing a similar issue?

**Comment by tylerlacroix** [comment]
Yeah, it was crashing every time I put my device to sleep in the login screen. Is it the "NSConcreteNotification unrecognized..." crash you're seeing?

**Comment by sleroux** [comment]
Yup looks like the same crash.

**Comment by tylerlacroix** [comment]
Yeah that crash was a weird one, it looked like when it was calling loadLogins(query: String? = nil) it tries to pass the an NSNotification in the parameter as a String and crashes.  Should be fixed in this patch though :)

**Comment by sleroux** [comment]
Just realized I made a similar patch for the selector bug and forgot about this one https://github.com/mozilla/firefox-ios/pull/1888. I would just remove the selector changes from this patch and I'll give this another test.

**Comment by tylerlacroix** [comment]
Okay, I removed it :)

**Pull request merged**
