### PR TITLE
Bug 1221594 - Login Detail Screen

### PR DESCRIPTION
**Pull request by sleroux**
* Introduces the LoginDetailViewController
* Currently READONLY and missing favicon (will be resolved with favicon patch)

### CODE REVIEW

**Comment by sleroux** [comment]
Deletion, editing, and menu functions will come in later patches.

**Comment by fluffyemily** [comment]
The NativeRefTests had a bunch of failures. I added the logs to a gist here:

https://gist.github.com/fluffyemily/aed988b23b181f27682d

**Comment by fluffyemily** [comment]
For editing are you going to create a new VC or just make this one editable? If making this one editable, how about making the `UILabel`s for username and password non-editable `UITextField`'s. Then for password you can set `secureTextEntry = true` to get the text obscuring for free (and using a custom font to get the right obscuring text). Then for edit all you have to do is make those text fields editable and away you go....

**Comment by sleroux** [comment]
I'm going to use the same VC for editing. I have another branch I started doing the editing work on where I've swapped out the description UILabels with UITextFields here: https://github.com/mozilla/firefox-ios/commit/a3ea92eecf7d030e360a65c6ac844da737b7e8ed

I forgot that UITextField has the secureTextEntry property - I'll definitely use that instead of my wonky extension.

**Pull request merged**
