### PR TITLE
Bug 1136319 - Tap below location bar to hide keyboard

### PR DESCRIPTION
**Pull request by matthewpurcell**
Fix for bug 1136319 (hide the keyboard immediately on tap down anywhere in the area under the location bar).

Implemented a `UIGestureRecognizer` on the `BrowserViewController` which detects taps. The gesture recognizer will only fire if the URL text field is first responder (i.e. the keyboard is on-screen and it's for the URL text field) - this has been done in case (in the future) there are other text fields in the view controller for which we do not want this behaviour.

The gesture recognizer will also not fire if the `urlBar` itself is tapped. There didn't actually seem to be any problems with this happening, but better to be safe than sorry later.

Two new public methods were added to the `URLBarView` class allowing the keyboard to be dismissed and the first responder status of the text field to be determined, without the need to expose the text field itself.

Note, when the user taps under the location bar (and dismisses the keyboard) the `urlBarDidEndEditing` delegate method is **not** called, mainly because the current implementation of this method (i.e. in `BrowserViewController`) does things we don't really want to happen, as we just want to dismiss the keyboard.

### CODE REVIEW

**Comment by thebnich** [comment]
Playing around with this a bit, I noticed that the keyboard gets dismissed when I tap Yes or No to enable search suggestions. We wouldn't want to do that since the user is in the process of typing a query, and there's a good chance they'll continue to type after making their preference.

I think there's only one view that we care about hiding the keyboard when touched, and that's the home panel top bar. Rather than a catch-all approach where we hide the keyboard whenever _anything_ below the URL bar is tapped, it might be safer to explicitly attach to the view(s) that should trigger the keyboard to hide. The potential downside is that we'll have to reimplement this behavior whenever we add other views that we'd want to hide the keyboard, but we can cross that bridge when (or if!) we come to it.

So as an alternative fix, I suggest attaching a touch listener to the `buttonContainerView` in `HomePanelViewController`, then dismissing the keyboard from there. I'm not sure whether there's a good way to resign the first responder without having a reference to the view, so this might require adding a `homePanelHandleDismissKeyboard` callback to `HomePanelDelegate`.

**Comment by matthewpurcell** [comment]
Thanks for the feedback @thebnich . Following your suggestion, I changed the gesture / touch recognizer such that it's now attached only to the `buttonContainerView` in the `HomePanelViewController` so that it is no longer a catch-all approach.

I implemented a new delegate callback method as part of the `HomePanelViewControllerDelegate` protocol called `homePanelViewControllerHandleDismissKeyboard:` which is implemented in the `BrowserViewController` to resign the `URLBarView` text field when called (as we have a reference to that view from the `BrowserViewController` class).

**Comment by thebnich** [comment]
Thanks for the updated PR! Instead of doing the dance with `URLBarView` and `BrowserViewController`, I wonder if it would be more straightforward for `HomePanelViewController` to simply dismiss the keyboard directly, without caring who the responder is.

Perhaps we could simply add a generic "close keyboard" snippet, similar to what we do [here](https://github.com/mozilla/firefox-ios/blob/fe0339d57850988673efa524a1a79aa1c132b766/Client/Frontend/Home/TopSitesPanel.swift#L70). Sorry for not suggesting that before -- that bit was added after my last comment as part of #267. Does that approach make sense to you?

**Comment by matthewpurcell** [comment]
Thanks @thebnich for the feedback and advice. Wow, the solution is now much simpler compared with the first commit :)

I originally didn't opt for `endEditing` since it's a fairly heavy-handed approach and I wasn't familiar enough with the codebase to know whether it would cause problems down the track (similar for the reasons behind originally making a reasonably general solution to this bug - tapping anything underneath the location bar, rather than just the home panel). However, this is a much better solution, particularly if it's being used successfully in other parts of the code.

**Comment by thebnich** [comment]
Thanks, looks great! Squashed and pushed 3f44232.

**Pull request closed without merging**
