### PR TITLE
Bug 1273778 - adds separate class extension

### PR DESCRIPTION
**Pull request by tiagomartinho**
- adds separate class extension in BackForwardListViewController for the
table view protocol methods in order to adhere to the swift style guide

### CODE REVIEW

**Comment by AaronMT** [comment]
Sorry for the delay, we should get this reviewed (@thebnich ?)

**Comment by thebnich** [comment]
Hi @tiagomartinho, do you mind filing a bug and linking the bug number to this PR? See [this section in the README] for more information. Thanks!

**Comment by tiagomartinho** [comment]
I filled the bug and linked it to this PR. I was not able to set @thebnich as reviewer thought, it said you haven't logged into the platform for 60 days. Thank you!

**Comment by thebnich** [comment]
Looks good. Thanks!

Merged 6d5d83b5faa59e80d02f7986607e4a1cfa82d590.

**Pull request closed without merging**
