### PR TITLE
Bug 1241586 - Fixed protection space query to use full URL instead of just host

### PR DESCRIPTION
**Pull request by sleroux**
After resolving the basic auth bug where we would only save hostnames and not include the scheme, this query broke as it relied on using only the host. I've updated the query to now properly use the full URL.

### CODE REVIEW

**Comment by rnewman** [comment]
Do we do the same thing anywhere else?

**Comment by sleroux** [comment]
Took another look and added the schemeless host to the query in cases where we still have those in the DB. 

Also noticed something off with the args/query we were making. The `usernameMatch` var wasn't being used in the query and the args didn't match up in the case where `username IS NULL`. Unless I'm missing something I think we should be using `usernameMatch` in both subqueries?

**Comment by sleroux** [comment]
Added UITest for new and new/update scenarios.

**Comment by rnewman** [comment]
Good catch!

**Comment by rnewman** [comment]
Beautiful. Merging this.

**Pull request merged**
