### PR TITLE
Bug 1182488 - Changing theme color in ReaderView crashes the app

### PR DESCRIPTION
**Pull request by taher-mosbah**

### CODE REVIEW

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 17 seconds.
? build errors: checkout-error

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 17 seconds.
? build errors: checkout-error

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 17 seconds.
? build errors: checkout-error

**Comment by taher-mosbah** [comment]
I messed up this pull request, I'm making two separate ones for each bug.

**Pull request closed without merging**
