### PR TITLE
Bug 1189127 - Use canAutocomplete instead of willSet to filter deletions

### PR DESCRIPTION
**Pull request by thebnich**

### CODE REVIEW

**Comment by thebnich** [comment]
@codestergit, feel free to give feedback if you want since you have a lot of experience with this code :)

**Comment by codestergit** [comment]
Hi @thebnich 
This patch is really great and we can get rid of search query caching.
But while testing I have found first time `canAutocomplete` will be `false` as we are entering text at beginning not end so `range.location` check will fail.
I think we should remove `range.location == count(text)` as we also want completion if user enters text in middle of text or copy/paste in between. I have seen this behaviour in safari and we do not need for extra check to handle above case. 
For eg: user type `goole` and go back and enters `g` before `l` than we should show auto completion. This is behaviour previous to [Bug-1166781] (https://bugzilla.mozilla.org/show_bug.cgi?id=1166781)

**Comment by codestergit** [comment]
We can also remove [this line] https://github.com/thebnich/firefox-ios/blob/autocomplete-quick-delete/Client/Frontend/Widgets/AutocompleteTextField.swift#L74
and 
https://github.com/thebnich/firefox-ios/blob/autocomplete-quick-delete/Client/Frontend/Browser/URLBarView.swift#L622
which was previously added for clearing cached search query.

**Comment by thebnich** [comment]
@codestergit, thanks for the feedback!

> We can also remove this line https://github.com/thebnich/firefox-ios/blob/autocomplete-quick-delete/Client/Frontend/Widgets/AutocompleteTextField.swift#L74

I don't think we can remove this one. If I type "y", then touch the text field to complete to "yahoo.com/", we want the bottom search results to update for "yahoo.com/".

> https://github.com/thebnich/firefox-ios/blob/autocomplete-quick-delete/Client/Frontend/Browser/URLBarView.swift#L622
> which was previously added for clearing cached search query.

Thanks, removed.

**Pull request merged**
