### PR TITLE
Bug 1177493 - When you refresh the settings page when signed in, unwanted headers appear at the top

### PR DESCRIPTION
**Pull request by bkmunar**
added a line to clip header so that it doesn't show up after refresh

### CODE REVIEW

**Comment by st3fan** [comment]
lttm

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 10 minutes and 52 seconds.
16 build errors: build-errors

**Comment by bkmunar** [comment]
lttm

**Comment by sleroux** [comment]
I'm down with merging this in since it does fix the bug but we need to revisit the settings view controller because we're not doing recycling correctly and the code is a bit messy. We might see problems later on as we extend this.

**Comment by darrinhenein** [comment]
Cherry-picked into https://github.com/mozilla/firefox-ios/pull/665

**Pull request closed without merging**
