### PR TITLE
Bug 1222848 - Bookmark titles should be editable 

### PR DESCRIPTION
**Pull request by fruitcoder**

### CODE REVIEW

**Comment by fluffyemily** [comment]
The overall implementation is good. Just need to be a bit more careful with force unwrapping things and localizing all the strings.

**Comment by thebnich** [comment]
Merged the highlight portion of this ([bug 1208564](https://bugzilla.mozilla.org/show_bug.cgi?id=1208564)) in 5b15103.

**Comment by sleroux** [comment]
@tylerlacroix Does this patch overlap with the work in progress in the bookmarks management UI you worked on last month for https://bugzilla.mozilla.org/show_bug.cgi?id=1243019? If so it would be great to see if we can consolidate this stuff.

**Comment by tylerlacroix** [comment]
@sleroux I looked over this patch and I'm not sure I can integrate this code because it looks like my patch overlaps this code.  The bookmark table code has changed since this was written, and the UI is pretty much done in my patch.

**Comment by sleroux** [comment]
@tylerlacroix Thanks for taking a look!

> I looked over this patch and I'm not sure I can integrate this code because it looks like my patch overlaps this code. The bookmark table code has changed since this was written, and the UI is pretty much done in my patch.

Considering that this patch is out of date by 9 months and we have a PR open that has these changes against a newer version of the codebase, I'm going to go ahead and close this PR.

@fruitcoder If you're interested in picking this up again and/or extending it into more UI changes for bookmarks management let me know!

See https://github.com/mozilla/firefox-ios/pull/1857 for the additional bookmarks UI work from Tyler's branch.

**Pull request closed without merging**
