### PR TITLE
Ui update

### PR DESCRIPTION
**Pull request by tecgirl**
updated Aa button assets for Reading List Reader View.

### CODE REVIEW

**Comment by st3fan** [comment]
@tecgirl i think only half of these changes mde it into the project. is it easy for you to see which ones still need to be imported? I *think* it is just the reading view button image?

**Comment by thebnich** [comment]
I'll take a look to see if we can get this sorted out.

**Comment by tecgirl** [comment]
I believe I just overwrote all of that anyway, the right way, with pull 321. :-) 

-- 
Robin Andersen
Senior Mobile UX Designer, Firefox
robin@mozilla.com | irc:tecgirl | \m/

On April 7, 2015 at 2:53:15 PM, Brian Nicholson (notifications@github.com) wrote:

I'll take a look to see if we can get this sorted out.

**Comment by thebnich** [comment]
Sounds like this PR is no longer needed, so closing it out.

**Pull request closed without merging**
