### PR TITLE
Bug 1170382 - Use a forked Deferred library

### PR DESCRIPTION
**Pull request by wesj**
I had to fork deferred here because its a final class (i.e. we can't extend it). It also had some strangeness with initializers that I changed. I sent both PRs upstream:

https://github.com/bignerdranch/Deferred/pulls

I'm not that hoepful they'll be taken, since these seem like conscious decisions. We could probably do some strange hacking to wrap a Deferred here or maybe use an extension. None of those solutions seemed clean.

### CODE REVIEW

**Comment by wesj** [comment]
lttm

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 2 minutes and 49 seconds.
23 build errors: build-errors

**Comment by fxios-buildasaur** [comment]
Result of integration 2
Integration took 14 minutes and 3 seconds.
All 131 tests passed, but please fix 30 warnings.

**Comment by wesj** [comment]
Rnewman gave a verbal r+ to this change in triage. Taking it!

**Pull request merged**
