### PR TITLE
Bugs 1120827, 1120831: Improve accessibility

### PR DESCRIPTION
**Pull request by dusek**
Add accessibility labels etc. for buttons and other elements whose function is conveyed mostly visually. Also provide VoiceOver scrub gesture where convenient.

Submitted under MPL v2.0 by my employer, A11Y LTD.

### CODE REVIEW

**Comment by thebnich** [comment]
Thanks for the PR! Can you please <a href="https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody%40mozilla.org&bug_file_loc=http%3A%2F%2F&bug_ignored=0&bug_severity=normal&bug_status=NEW&cf_fx_iteration=---&cf_fx_points=---&component=Browser&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&defined_groups=1&flag_type-4=X&flag_type-607=X&flag_type-791=X&flag_type-800=X&flag_type-803=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=iOS%207&priority=--&product=Firefox%20for%20iOS&rep_platform=All&target_milestone=---&version=unspecified">file a bug</a>, then update the title of this PR to reference that bug #? You can use the other open PRs as a reference if helpful.

**Comment by dusek** [comment]
Thanks for the quick turnaround. I did:

- submit [the](https://bugzilla.mozilla.org/show_bug.cgi?id=1120827) [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1120831)
- reference them in the title of the PR
- reference them in individual commit message titles
- rebased on current master while I was at it
- added note to this PR that we are OK with MPLv2.0

Please let me know if there is anything else to make a contribution properly, it's my first time contributing to Mozilla. :-)

**Comment by dusek** [comment]
I made some updates:
- rebased to latest code
- reflected latest code (address field becomes address and search field)
- added accessibility label to avatar image, secure connection image, reader button, search suggestions for search engines

**Comment by thebnich** [comment]
Thanks for the contribution!

Unfortunately, it looks like this got bitrotted by #100. Would you mind rebasing this PR so we can merge it?

**Comment by dusek** [comment]
> Would you mind rebasing this PR so we can merge it?

Done.

**Comment by thebnich** [comment]
Looks great, thanks!

**Pull request merged**
