### PR TITLE
Bug 1250103 l10n snapshot test clear private data

### PR DESCRIPTION
**Pull request by fluffyemily**
* add identifiers to items so they can be referenced without labels

for https://bugzilla.mozilla.org/show_bug.cgi?id=1250103

### CODE REVIEW

**Comment by sleroux** [comment]
Looks good but when I run the `testClearPrivateData` snapshot test it fails entering the fake credentials into FxA sign in by only entering a password but not the email field. Are you seeing this too?

**Comment by fluffyemily** [comment]
That's irritating. I was trying to account for the situation when, after log out, it only provides a password field and not the email field. Will take another look as obviously that prevented the first case (both email and password required) from working.

**Comment by fluffyemily** [comment]
No, that works for me. Hmm.

**Comment by sleroux** [comment]
Works for me now after the expectation timeout!

**Pull request merged**
