### PR TITLE
Bug 1118127 - "settings" icon isnot highlight.

### PR DESCRIPTION
**Pull request by hirohisa**
- bugfix, go-out current mark in tabs bar on changing tabs' enable/disable on settings

### CODE REVIEW

**Comment by thebnich** [comment]
@hirohisa, can you please <a href="https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody%40mozilla.org&bug_file_loc=http%3A%2F%2F&bug_ignored=0&bug_severity=normal&bug_status=NEW&cf_fx_iteration=---&cf_fx_points=---&component=Browser&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&defined_groups=1&flag_type-4=X&flag_type-607=X&flag_type-791=X&flag_type-800=X&flag_type-803=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=iOS%207&priority=--&product=Firefox%20for%20iOS&rep_platform=All&target_milestone=---&version=unspecified">file a bug</a> and update this PR to reference that bug # (instead of "XXX")?

**Comment by thebnich** [comment]
Thanks! Can you post the steps to reproduce the NSRangeException that your first commit fixes?

@wesj might be a good reviewer for this since I think he wrote the settings button handling.

**Comment by hirohisa** [comment]
@thebnich, Thanks comment. If you import only second commit, it reproduce. so I think commits change the order between first commit and second commit?

**Comment by hirohisa** [comment]
Thanks @wesj for review. I pushed it that includ maring logic into updateButtons.

**Comment by hirohisa** [comment]
Thank @wesj ! Sorry, I dont know `buttons[selectedButtonIndex].item`. It's better! I pushed.

**Pull request closed without merging**
