### PR TITLE
Bug 1162323 - Fix the sizes of the settings and add tab buttons

### PR DESCRIPTION
**Pull request by thebnich**

### CODE REVIEW

**Comment by sleroux** [comment]
Changes look good :+1:

**Comment by thebnich** [comment]
@sleroux thanks for the quick review!

You can "officially" flag a patch as r+'d by going to [the bug in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1162323), clicking the <b>Details</b> link next to the PR attachment, then flipping <b>review</b> from <b>?</b> to <b>+</b>.

Sorry for the cumbersome system...we tie everything back to Bugzilla since that's what product/release management, QA, and most of the company pay attention to.

**Comment by sleroux** [comment]
Oops I submitted another attachment with review+ so you might see it twice on there.

**Comment by thebnich** [comment]
No problem -- you can mark patches as obsolete by clicking <b>Details</b>, <b>edit details</b>, then checking the <b>obsolete</b> checkbox (I just did that in the bug). That'll make it hidden.

**Pull request merged**
