### PR TITLE
Bug 1129505 - persist account state

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by ncalexan** [comment]
@rnewman: this makes the Firefox Account itself own writing the internal state into the keychain.  I took your "random label" approach; I liked it.  This works well for me locally.  It's not easy to move an Account's state yet, so you'll just have to test the success case -- and see if you hit clock skew or something else.

I wonder if we could tie the tab storage more explicitly to the account.  If you disconnect, you'll see the old tabs hanging around.  Perhaps we can do better?

**Comment by rnewman** [comment]
We actually *do* tie tab storage more explicitly to the account, right there — you get access to tabs via Sync and only via Sync.

We need to finish doing so, but that's as simple as making the no-account state return nothing, rather than falling back to querying the DB.

Eventually we'll realize my vision of having access to most profile data be intermediated by Sync.

**Comment by rnewman** [comment]
See #339.

**Comment by rnewman** [comment]
This looks good to me.

**Comment by ncalexan** [comment]
Landed.

**Pull request closed without merging**
