### PR TITLE
Bug 1162174 - Added 1Password support

### PR DESCRIPTION
**Pull request by radazzouz**
This pull request should address [Bug 1162174](https://bugzilla.mozilla.org/show_bug.cgi?id=1162174).

1Password will now appear in the share sheet (if installed and if enabled) the same way it does it Mobile Safari.

You can now fill your Logins, Credit Cards and Identities into Firefox for iOS. You can also create new Logins for the current website using the 1Password extension.

**The share sheet**

**The 1Password extension**

### CODE REVIEW

**Comment by st3fan** [comment]
lttm

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 13 minutes and 50 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by fxios-buildasaur** [comment]
Result of integration 2
Integration took 11 minutes and 7 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by radazzouz** [comment]
Addressed! Sorry my bad. I was testing with the current beta version of 1Password and not the App Store version.

**Comment by fxios-buildasaur** [comment]
Result of integration 3
Integration took 11 minutes and 14 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by fxios-buildasaur** [comment]
Result of integration 4
Integration took 14 minutes and 25 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by radazzouz** [comment]
Please do not merge until 1Password 5.5 comes out :wink:

**Comment by radazzouz** [comment]
Hi @jpvasquez and @st3fan ,

Thanks for the suggestion :+1: 

The 1Password extension is a generic extension (not limited to `findLoginForURLString:`), therefore its Bundle ID does not contain the `.find-login-action.` substring.

`org.appextension.find-login-action` is the item provider's type identifier (see [line 516 of `OnePasswordExtension.m`](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L516)) and it is not meant to be used as a password manager's extension's bundle ID. Unless the extension in question only supports the [Use Case #1: Native App Login](https://github.com/AgileBits/onepassword-app-extension#use-case-1-native-app-login) of the [App Extension API](https://github.com/AgileBits/onepassword-app-extension).

Please note that the capability I added in this PR, does not use the [Use Case #1: Native App Login](https://github.com/AgileBits/onepassword-app-extension#use-case-1-native-app-login) , (a.k.a `org.appextension.find-login-action`) at all . Instead, it uses the [Use Case #4: Web View Filling Support](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-filling-support) which uses `org.appextension.fill-browser-action` as the item provider's type identifier.

Hope that this helps :-)

Best,

**Comment by jpvasquez** [comment]
Pwsafe is also generic, supporting all ext points offered by the one password sdk, including both ones to fill a web view. 

The thing with the bundle id is because Chrome
checks for it that way. Without a bundle-ID like this, it won't send the required payload to the extension, except for one-password's, whose bundle-I'd has been hard-coded and grandfathered by Google's developers.

**Comment by jpvasquez** [comment]
I just reviewed the pull request. The code is correct, but the comments and strings are not. The activity type is not a bundle identifier, the activity type is an activity identifier. As far as
I can foresee, the current code should work with all one-password-sdk compatible pw managers. That couple of lines mentioning the bundle id of other password managers isn't needed, unless you wish to support other types of password managers extensions. In that case, you won't be looking for bundle identifiers, but for activity Ids instead.

**Comment by fxios-buildasaur** [comment]
Result of integration 5
Integration took 9 minutes and 31 seconds.
All 124 tests passed, but please fix 14 warnings.

**Comment by radazzouz** [comment]
Hi @jpvasquez ,

> Instead of self , you could put extensionItem directly in the activityItems array. If you do that, then you won't need to check for the bundle-id, i.e., you won't need to implement the UIActivityItemSource protocol.

If we do not do the bundle identifier check (`isPasswordManagerActivityType`) at all, there is a high risk of breaking other potential Action Extensions. In an attempt to be good citizens to activities, we believe that the safest way is to preserve the current implementation specific to password managers and allow other Action Extensions to use the activity view controller’s `completionWithItemHandler`.

> Since other activities do not return actionable data (if any at all) to the completionWithItemHandler callback.

This is a presumption that we should not make. We don’t know what other activities the Firefox team will want to add to this activity view controller. We could also have other activities (Action Extensions) which are not explicitly added in the code to the activity view controller. For example a translator Action Extension similar to the one demoed by Apple during WWDC 2014.

The entire purpose of the `isPasswordManagerActivityType` function is to limit web view filling to password managers which support [Use Case #4: Web View Filling Support](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-filling). Other action extension should not perform `fillReturnedItems`.

The original intent of the local function, `isPasswordManagerActivityType`, was to limit `fillReturnedItems` to extensions that conform to the [Web View Filling Support](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-filling) capability of the **App Extension API**. Other password managers were meant to update it (`isPasswordManagerActivityType`) with their bundle identifier in subsequent PRs as they add support on their end, as seen below:

```swift
	private func isPasswordManagerActivityType(activityType: String?) -> Bool {
		var isOnePassword = OnePasswordExtension.sharedExtension().isOnePasswordExtensionActivityType(activityType)
		var isPasswordManager = (activityType == "bundle.identifier.for.another.password.manager")
		return isOnePassword || isPasswordManager
	}
```

@st3fan, is there any reason why we shouldn’t go on with this approach?

Based on the above, do you think that the labels of the PR are accurate? This PR does not require any further changes, as far as I am aware of. In my opinion it can be merged in its current state as soon as 1Password 5.5 hits the shelves.

Thank you :smile:

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 18 seconds.
? build errors: checkout-error

**Comment by jpvasquez** [comment]
@radazzouz 

> If we do not do the bundle identifier check (isPasswordManagerActivityType) at all, there is a high risk of breaking other potential Action Extensions. In an attempt to be good citizens to activities,

Not really. The extension has to ask for a specific data type before fetching whatever has been put in the extension item. Like this:

```Swift
          if(itemProvider.hasItemConformingToTypeIdentifier(kUTTypeAppExtensionFindLoginAction))
          {
            self.loadAppDataFromExtensionHost(itemProvider, mode: .FindLogin, typeIdentifier: kUTTypeAppExtensionFindLoginAction)
            return
          }
          else if(itemProvider.hasItemConformingToTypeIdentifier(kUTTypeAppExtensionChangePasswordAction))
          {
            self.loadAppDataFromExtensionHost(itemProvider, mode: .ChangePassword, typeIdentifier: kUTTypeAppExtensionChangePasswordAction)
            return
          }
          else if(itemProvider.hasItemConformingToTypeIdentifier(kUTTypeAppExtensionSaveLoginAction))
          {
            self.loadAppDataFromExtensionHost(itemProvider, mode: .SaveLogin, typeIdentifier: kUTTypeAppExtensionSaveLoginAction)
            return
          }
          else if(itemProvider.hasItemConformingToTypeIdentifier(kUTTypeAppExtensionFillWebViewAction))
          {
            self.loadAppDataFromExtensionHost(itemProvider, mode: .FillWebView, typeIdentifier: kUTTypeAppExtensionFillWebViewAction)
            return
          }
          else if(itemProvider.hasItemConformingToTypeIdentifier(kUTTypeAppExtensionFillBrowserAction))
          {
            self.loadAppDataFromExtensionHost(itemProvider, mode: .FillWebView, typeIdentifier: kUTTypeAppExtensionFillBrowserAction)
            return
          }
```

The idea behind the `UIActivityItemSource` protocol used to supply the extension data afterwards is to avoid a eventual high processing cost to fetch or convert data. For example, if you need to extract all the webpage text for translation (see below). This protocol is not meant for the host app to find out what the extension wants. This is done via the types you send to the action sheet.

>> Since other activities do not return actionable data (if any at all) to the completionWithItemHandler callback.
> This is a presumption that we should not make. We don’t know what other activities the Firefox team will want to add to this activity view controller. We could also have other activities (Action Extensions) which are not explicitly added in the code to the activity view controller. For example a translator Action Extension similar to the one demoed by Apple during WWDC 2014.

1. The returned data type's is plist, which is really generic. But you can check the contents to see if it's a dictionary and if it contains the keys you need

2. The translation extension will not work in Firefox. Safari has a unique capability to inject a javascript file from the action into the page and run it before and after the extension is invoked. This is not a capability third-party browsers can use. If you want a translation extension, you'll have to explicitly extract the data to be translated yourself, send it to the extension and then replace the extension results into the web view.

**Comment by radazzouz** [comment]
@jpvasquez, `findLoginForURLString:` does indeed return a dictionary to the host app and so does the 1Password capability that I am integrating here. The difference is that in the case of `findLoginForURLString:` we return a dictionary with the credentials (username and password) and for this capability we return a dictionary with a fill script which we inject (Javascript) into the given web view emulating the Safari capability (Credit Card and Identity filling too). Basically, this capability has nothing to do with `findLoginForURLString:`.

Make sure that you take a look at the definition of [fillReturnedItems:](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L282) and [executeFillScript:](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L417).

Hope that this helps :wink:

Best,

**Comment by jpvasquez** [comment]
@radazzouz, findLoginForURLString: is part of the host app, because it's part of the SDK you embed in it. The dictionary it returns comes from the extension, which can be OnePassword or otherwise (pwSafe, for instance, works with it).

In the case of filling web views, the extension also returns a dictionary to the host app, which then extracts a small JSON and integrates with a  hard-coded javascript (`OPWebViewFillScript`) to fill the items. And pwSafe's extension also works in this mode.

In any case, my point is still valid: 

1. There's no reason to delay sending the `org.appextension.fill-browser-action` payload, which is created using the call to `createExtensionItemForWebView()` . You can put it directly in `activityItems` array you'll pass to the activity sheet, thereby eliminating the need to implement `UIActivityItemSource` altogether.

2. When an extension send you data back (OnePasswords, pwSafe's, or any other type of extension you may support in the future), you can inspect the returned data to process it correctly. For instance, for the password filling script, this is the structure returned:

``` swift
// Web Fill Script Keys
let AppExtensionWebViewPageFillScript = "fillScript"

// construct jsonString according to what the One Password SDK expects

let result = [
        AppExtensionWebViewPageFillScript : jsonString!
      ]

let itemProvider = NSItemProvider(item: result, typeIdentifier: kUTTypePropertyList as? String)
let extensionItem = NSExtensionItem()
extensionItem.attachments = [itemProvider]

if let extensionContext = self.extensionContext  {
  // This send the results back to the host app
   extensionContext.completeRequestReturningItems(extensionItems, completionHandler: nil)
}
```

If you make these changes, Firefox will be able to work, out-of-the-box with any password manager which makes itself compliant with OnePassword's model, which includes pwSafe. I don't see what's to gain from needing to white-list passwords managers one by one, when they all present the same interface for browsers and other apps. 

That's the whole idea behind extensions: neither the extension nor the host app need to know one another. For instance, the iCab browser already does that. Since it supported OnePassword's extension model the way I'm describing, when I released pwSafe's extension, it just worked, without any need to modify iCab or pwSafe's extension. The same goes for many other apps which fill web forms, such as Tweetbot, which uses it to loging to Twitter.

Recaping: pwSafe's extension, apart from its bundle-id, is indistinguishable from OnePasswords from the host app perspective. They have the same capabilities and behave according to the same interface. Implementing the changes I suggest, you'll be able to support pwSafe and any other password manager which adheres to the same rules defined by Agile Bits (that was their declared intention).

The only reason why pwSafe's extension has that `find-login-action` in its bundle-id is because Google Chrome was already in the wild with that odd requirement, leaving me the choice to either wait for them to fix their app or change pwSafe's extension bundle-id immediately allowing my users who use Chrome to enjoy pwSafe's extension. pwSafe's extension is not limited to this action, it does everything that OnePassword's  does. As a matter of fact, its first version did not have that string in its bundle-id, and it worked with everything but Chrome.

If I failed to convince you or if I couldn't make myself clear enough, I would love to chat or talk with about this. I can even share my screen with you over Skype and show what happens from both sides (host and extension) using the sample apps and pwSafe's extension. Please write me to jorge at app77 dot com so that we can setup a time.

Cheers,

**Comment by jpvasquez** [comment]
@radazzouz I can also send you a promo-code of pwSafe and guide you through testing the setup I described, if you prefer. In that case, I can fork your repository and issue a pull-request against you. Just let me know.

Cheers,

**Comment by radazzouz** [comment]
Hello @jpvasquez,

> 1. There's no reason to delay sending the org.appextension.fill-browser-action payload, which is created using the call to createExtensionItemForWebView() . You can put it directly in activityItems array you'll pass to the activity sheet, thereby eliminating the need to implement UIActivityItemSource altogether.

We did try to implement something similar to your suggestions in the past and the results were unsuccessful:

Adding "org.appextension.fill-browser-action” to the activityItems array caused some share activities/extensions disappear from the share sheet. See [issue #141](https://github.com/AgileBits/onepassword-app-extension/issues/141)

That is why we are using the UIActivityItemSource protocol and the current implementation. We also took the time to create a gist about adding the 1Password Extension to a custom UIActivityViewController.

The proposed implementation  for FireFox uses that gist as a guideline. The gist comes with Swift and Objective-C sample apps. I’d be awesome if you could modify those sample apps and “convince” me of a better solution ;-)

> 2. When an extension send you data back (OnePasswords, pwSafe's, or any other type of extension you may support in the future), you can inspect the returned data to process it correctly.

That is exactly what we are already doing in `fillReturnedItems:`. The thing is that if the completed activity item is not a password manager, we want to give it the chance to inspect the `returnedItems` array too. That is why we should explicitly check it’s a password manager (`isPasswordManagerActivityType:`). As I mentioned in one of my previous replies: Once, we merge this PR, each password manager which conforms to [1Password App Extension API](https://github.com/AgileBits/onepassword-app-extension), more specifically "org.appextension.fill-browser-action”, will have to add its extension bundle Identifier in `isPasswordManagerActivityType:`. It’s a one-liner PR for each password manager. Does this sound unreasonable?

Hope that this helps :-)

**Comment by jpvasquez** [comment]
@radazzouz and I just talked to one another directly and reached a common ground. 

Due to that [iOS bug](https://github.com/AgileBits/onepassword-app-extension/issues/141) @radazzouz describes on his last comment above, my proposed changes wouldn't work. 

Nevertheless, we decided to use `"password"` as a substring to be searched for in the activity extension bundle-id, avoiding the need to white-list password managers one by one, thus allowing developers to make their extensions compliant with Firefox (and other apps which use the SDK code), without the need to contact every known host app developer manually.

The commit above (https://github.com/radazzouz/firefox-ios/commit/b167894df84fd74f88d7974193fb9f8175f8883c) implements this.

Case closed, as far as I am concerned.

**Comment by radazzouz** [comment]
@jpvasquez :+1:

**Comment by jhugman** [comment]
I've rebased this PR and moved it to https://github.com/mozilla/firefox-ios/pull/1191 . Closing this one although the discussion here is valuable.

**Pull request closed without merging**
