### PR TITLE
Bug 1184783 - Change styling of top sites

### PR DESCRIPTION
**Pull request by wesj**
Blew this up a bit because I found some bugs in the old implementation. This tries a lot harder to find a "big" icon for a site. It does a few things:

1.) Tries open-graph icons. apple.com doesn't have a large favicon for us. This is the best it has AFAICT. OpenGraph icons are only used if there's no large <link> icon for a site. (Apple and Google seem to be the worst in terms of redirects and pages with no high quality icons).
2.) Looks for apple-touch-icon-precomposed. I left this out before.
3.) Uses AlamoFire for data loading. AlamoFire handles 302 redirects for us which is nice.
4.) Starts looking at other urls if the one given to it fails. If we get something like http://mail.google.com/something it will load it, look for icons. If everything it finds is small it'll look at http://mail.google.com/. If everything there is too small, it will look at http://www.google.com, so on with http://m.google.com and http://mobile.google.com. Its a long rabbit hole, but usually winds up finding us something.

I also revamped how these are shown a bit, but waiting for some UX feedback there. I'll post a screenshot.

### CODE REVIEW

**Comment by wesj** [comment]
https://www.dropbox.com/s/zcct28hrqdrig07/iOS%20Simulator%20Screen%20Shot%20Jul%2021%2C%202015%2C%203.42.03%20PM.png?dl=0

**Comment by wesj** [comment]
Same thing without the top sites changes:
https://www.dropbox.com/s/6rgnchi6yubtzto/iOS%20Simulator%20Screen%20Shot%20Jul%2021%2C%202015%2C%203.54.37%20PM.png?dl=0

**Comment by darrinhenein** [comment]
@wesj I can't get this branch to build, getting:

```
CpResource /Users/dhenein/Development/mozilla/mobile/Downloads/topsites.txt /Users/dhenein/Library/Developer/Xcode/DerivedData/Client-fmrtvitykvtqccaxmwrckupuijrx/Build/Products/Debug-iphoneos/FennecAurora.xctest/topsites.txt
    cd /Users/dhenein/Development/mozilla/mobile/firefox-ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/dhenein/Development/mozilla/mobile/Downloads/topsites.txt /Users/dhenein/Library/Developer/Xcode/DerivedData/Client-fmrtvitykvtqccaxmwrckupuijrx/Build/Products/Debug-iphoneos/FennecAurora.xctest

error: /Users/dhenein/Development/mozilla/mobile/Downloads/topsites.txt: No such file or directory
```

**Comment by wesj** [comment]
Oh thanks. That doesn't really need to be here, but I added it and updated this again. Try again?

**Comment by sleroux** [comment]
@darrinhenein I think this is the same as the current top sites layout we use right? Can we close this?

**Comment by darrinhenein** [comment]
@sleroux I think visually, yes. Don't want to lose any nice stuff in here re: open graph images or better icon-finding if it looks valuable, though... (not sure what/if any of this made it in elsewhere)

**Pull request closed without merging**
