### PR TITLE
History panel.

### PR DESCRIPTION
**Pull request by rnewman**

### CODE REVIEW

**Comment by st3fan** [comment]
lttm

**Comment by st3fan** [comment]
Result of integration 1
Integration took 6 minutes and 40 seconds.
All 124 tests passed, but please fix 13 warnings.

**Comment by fxios-buildasaur** [comment]
Result of integration 1
Integration took 11 minutes and 5 seconds.
All 124 tests passed, but please fix 13 warnings.

**Comment by fxios-buildasaur** [comment]
Result of integration 2
Integration took 13 minutes and 2 seconds.
All 124 tests passed, but please fix 13 warnings.

**Comment by rnewman** [comment]
Landed.

**Pull request closed without merging**
