### PR TITLE
Bug 1289146 – Firefox crashes when opening downloads in other apps

### PR DESCRIPTION
**Pull request by varkor**
I wasn’t quite sure where we wanted to place the popover, so it’s just
in the toolbar for now.

### CODE REVIEW

**Comment by sleroux** [comment]
Patch works but I'm a little concerned over the existing code we have for the `OpenInHelper` feature.

In the other cases of passbook/PDF, the openInView is a bar that runs along top (or bottom, I forget) of the browser that provides a button the user can tap on to either save to passbook or iBooks. The ShareFileHelper is unique in that it displays a popover. Looking at the existing code, the helper was not built with iPad in mind since the required `sourceView` of the popoverPresentationController was never set. Passing in the sourceView into `openInView` works but breaks the abstraction.

Instead of shoehorning in the `sourceView` into the `openInView` property I propose we rethink the factory abstraction here. Simplest approach would be to take the ShareFileHelper out of the OpenInHelper since doesn't really align with other open in options.

**Comment by varkor** [comment]
Oh, I misinterpreted what it was being used for! That makes sense — I'll take a different approach.

**Comment by varkor** [comment]
Is this a little closer to what you had in mind?

**Comment by sleroux** [comment]
When I run this, the downloads prompt displays every time I navigate to a website. I think something related to the logic changes in the decidePolicyForNavigationResponse got mixed up.

The more I look at the existing solution of using these helpers, the more I want to rethink the abstraction. One of the motivations behind putting these in helper objects was to try to reduce the amount of code in the `BrowserViewController` but I think the cost is in weak abstraction over handling unsupported MIME types. I'm not sure what the solution looks like yet though. 

I think the best course forward would be to stick with the original patch and file a follow up to reconsider how we have unsupported MIME types in general.

**Comment by varkor** [comment]
Oops. I've addressed that. Do you still think it'd be best just to use the original solution?

**Comment by sleroux** [comment]
> Do you still think it'd be best just to use the original solution?

Yea I think so.

**Comment by varkor** [comment]
I've reverted the changes. If you think of a better way to restructure the resource MIME type handling, I'd be happy to try restructuring the code to make it feel a bit more cohesive.

**Comment by sleroux** [comment]
Only thing I would change is having the pop over appear from the share button in the URL bar instead of the text field:

screenshot 2016-08-02 09 24 03

**Comment by varkor** [comment]
That does seem like a more sensible location to put it!

**Pull request merged**
