### PR TITLE
Bug 1169143 Change the UISwitch tintcolor for the SearchSettingsTableView

### PR DESCRIPTION
**Pull request by xusader**
Change the UISwitch tintcolor for te searchsettings

### CODE REVIEW

**Comment by xusader** [comment]
Change the search settings uiswitch tintcolor

**Comment by st3fan** [comment]
@xusader can you please rebase this? it does not compile on master for me.

**Comment by xusader** [comment]
@xusader 	Update SearchSettingsTableViewController

**Comment by xusader** [comment]
https://github.com/mozilla/firefox-ios/commit/115bbaf7a88c2f2e93545d5503cd9bcd3ce5d126

**Comment by st3fan** [comment]
@xusader I don't think the rebase worked out well because I still get some compile errors when I try to compile your PR branch. But it is ok, those errors were pretty minor and not in your code. I merged your patch.

No more green switches in the search settings! Thank you very much for the contribution.

**Comment by xusader** [comment]
Thanx!!!

**Pull request merged**
