### PR TITLE
Make search list results display in sections

### PR DESCRIPTION
**Pull request by lyle-luan**
I am not sure if we need bookmarks&history here, I'm not even sure if these are what Mozilla want.

### CODE REVIEW

**Comment by wesj** [comment]
Yeah, we don't really have any mockups from UX on this yet. I was looking at making these a unified list in https://github.com/mozilla/firefox-ios/pull/104 but this feels pretty clean (and both seem a lot better than whats in right now).
One nice thing about the single cursor is that we can intermix different types of rows and use accessory icons/views on the right hand side to designate the row type (that's what we do on Android right now as well...) I wonder if we can UX to weigh in on what they'd like to move towards.

**Comment by darrinhenein** [comment]
@wesj I'd love to weigh in :) Do you think you could attach a screenshot or a clearer description of what the question is? I'm guessing this is regarding the list that appears while editing the url field... I would say on first thought we'd want something similar to desktop and Android, where a combination of history, bookmarks and search results are presented (the goal here is to just let the user get to where they're trying to as quickly as possible).

**Comment by wesj** [comment]
Sure. Right now this looks like: https://www.dropbox.com/s/ecvhntd7r6h1r5d/sections.png?dl=0

We can (obviously?) customize the section headers, or probably hide them if we want. That would bring us in line with Android (after I finish adding bookmarks in here)

**Comment by darrinhenein** [comment]
(Firstly, :+1: for screenshots in PRs!)

I think one design showed the one-off searches as just icons across the top, similar to our one-off search on desktop (no need to repeat the term 10 times)... and I think row decorations for bookmarks/history items probably eliminate the need for section headers. Will get a mockup to you asap.

**Comment by lyle-luan** [comment]
I forget the Bookmarks! I will fix it after 22 hours. **SORRY!**
BTW, as I mentioned in my commit(0f50ea2), I got error when I access to history:
``Err: Error Domain=org.mozilla Code=1 "SQL error or missing database no such column: history.id" UserInfo=0x7ffb8302bea0 {NSLocalizedDescription=SQL error or missing database no such column: history.id}``

**Comment by wesj** [comment]
Yeah. That should be fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1128363 if it ever gets reviewed. If you reset you simulator, it should also work.

**Comment by wesj** [comment]
I didn't see you updated this. I rebased it and all appears good! I'm going to land the rebased version.

**Comment by lyle-luan** [comment]
Sorry, I am spending my happy time of Chinese New Year :]
Thank you for the merge, I will come back. ;]

**Pull request merged**
