### PR TITLE
Bug 1129158 - persist account

### PR DESCRIPTION
**Pull request by ncalexan**
@st3fan @rnewman here is some early hatchet work.  Next is to make an `Account` owned by the `Profile`.  Early feedback appreciated.  @st3fan if you have some elaborate plan for managing profiles, accounts, and the extensions, now's the time.  Otherwise I'm going to tear out and we'll rebuild later.

### CODE REVIEW

**Comment by st3fan** [comment]
Looks good to me. I'm not a reviewer for this bug but I would give a +r :-)

**Comment by shaleengarg** [comment]
Hello Everyone,
I am a newbie to the world of open source and github.I have just started to
use github now and I want to contribute to mozilla.
I know decent programming in C and have started to learn python.Please
guide me through . I would be very greatful to all the contributors of
Mozilla.
Thankyou

On Fri, Feb 6, 2015 at 7:23 PM, Stefan Arentz <notifications@github.com>
wrote:

> Looks good to me. I'm not a reviewer for this bug but I would give a +r :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/firefox-ios/pull/135#issuecomment-73238993>.
>



-- 
*shaleen*

**Comment by st3fan** [comment]
@shaleengarg Hi there! All our bugs and tasks are in Bugzilla. We currently do not have a whole lot of bugs that are marked as good starter bugs, but we will work on that. If you want to make a contribution then I would suggest to start playing around with the Swift programming language.

**Comment by ncalexan** [comment]
@st3fan has already given r+ to parts 1 through 6.  Those are straight clean-up.  @st3fan or @thebnich, could one of y'all look at Part 7, which imports a modified version of https://github.com/jrendel/SwiftKeychainWrapper.  You can see that I essentially use it as a key-value store for a single key, so I'm not wedded to it and we could easily replace it or roll our own.  Finally, perhaps @rnewman could look at Part 8 and say "yes, persistence in Swift is awful".

I apologize for all the TODO items, but I spent most of 3 days fighting Swift to do a 3 hour task and it's better to iterate than get everything perfect.

**Comment by ncalexan** [comment]
I think the travis build failure is because I deleted stuff that was maybe a git submodule?  @st3fan might know better?

**Comment by ncalexan** [comment]
Finally, I tested this in the simulator (and it persists the account across simulator restarts), but I didn't test on a device.  I think we may have issues on device because the extensions (Share and SendTo) require Profiles -> Account -> KeyPair -> the FxA framework, which produces a warning.  Again, I don't know what the way forward is here.

**Pull request closed without merging**
