### PR TITLE
No bug - remove outdated exclude_signup comment for FxA

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
@ncalexan r?

**Comment by vladikoff** [comment]
The URLs were adjusted here: https://github.com/mozilla/firefox-ios/commit/6ed848cc4897257ea296e2d21b4aaa6c0ba0a222 but the comment remained

**Comment by vladikoff** [comment]
ping @ncalexan @rnewman

**Comment by ncalexan** [comment]
Sorry, I get lots of GitHub spam so don't always see my @ mentions.  Ship it.

**Comment by vladikoff** [comment]
> Sorry, I get lots of GitHub spam so don't always see my @ mentions. Ship it.

Ah no worries, you'll have to merge this though I cannot do it.

**Pull request merged**
