### PR TITLE
Bug 1243847 - Search import script improvements

### PR DESCRIPTION
**Pull request by thebnich**
I gave a summary of most commits in the commit messages, but here's a quick overview:

The first four commits remove some of the manual work involved with the existing scripts. These commits merge the scraper scripts into one, automate creation of the `en` search directory, automatically filter out unsupported locales, and automatically deletes/recreates the `SearchPlugins` directory each time the script is run.

The fifth commit is the important one: it allows us to create overlay XML files for making iOS-specific modifications without having to modify the engines themselves. In other words, we can now re-run the import script at any time without losing our local changes.

I noticed when parsing/writing XML files, the script made some unrelated formatting changes to the engine files. I reformatted the existing search engines and committed those changes in the sixth commit to make the following commit (with meaningful changes) easier to review.

Commit 7 contains the newly imported search engines. For the most part, local changes that were already in the tree that were moved into overlays don't show up in the diff here, which is good -- that means the engines after applying the transformations are roughly the same as the engines we had already. As a result, the changes committed here are the actual updates since the last time we did an import from Android.

Commit 8 simply moves search-related files from `Assets` into `Assets/Search` to keep things more logically grouped.

Finally, the last commit adds a README outlining the entire process.

### CODE REVIEW

**Comment by thebnich** [comment]
Note that the `SearchOverlays/wikipedia.xml` overlay (which includes an updated Wikipedia icon) and the `SearchOverlays/zh-CN/list.txt` override (which changes the list of zh-CN engines) should probably be pushed upstream to the Android repos since these don't seem iOS-specific.  I'll make sure the appropriate bugs are filed.

**Comment by rnewman** [comment]
Really nice work. :+1:

**Comment by thebnich** [comment]
> Is this sufficient? I'm particularly thinking of Java's need to translate Hebrew (iw :arrow_right: he), Indonesian (in :arrow_right: id), and Yiddish (ji :arrow_right: yi).

Good observation; filed [bug 1253045](https://bugzilla.mozilla.org/show_bug.cgi?id=1253045).

**Comment by thebnich** [comment]
Merged with comments addressed and some basic tests: ca841af

**Pull request closed without merging**
