### PR TITLE
Bug 1141850, Bug 1248790, Bug 1249429, et al — Bookmark all the things. 🙌

### PR DESCRIPTION
**Pull request by rnewman**
Read these two gists before attempting to review this code.

- https://gist.github.com/rnewman/f95720050df3d5515351
- https://gist.github.com/rnewman/82c17460161047db38d5

This PR includes the following, in order:

- Bridging `MaybeErrorType`. We should have done this sooner.
- The already-reviewed schema and storage changes for bookmarks (Bug 1201110), along with review comments and corrections.
- The implementation of Bug 1233193 to support recursive deletion of bookmark folders. This isn't well-tested, and I haven't added Bug 1232810 yet, and so it's not yet enabled — you can only delete non-folders in this branch. See the end of this list.
- Three-way bookmark tree merging, complete with a buffering synchronizer, strong validation, and staged application. See Bug 1141850 for remaining things to do, but this syncs my profile correctly, along with bidirectional changes and conflict resolution. Part 3 is big, Part 4 is the meat. The merger is very, very well-commented and tries to be as non-clever as possible in its implementation, but it's 1500 lines of Swift and has to deal with a lot of pain.
- Bug 1248790, removing the default bookmarks from the bookmark list. This involved a change to our separator line drawing to avoid crashing when there's nothing at the bottom.
- Bug 1249249, which enables swipe-to-delete for all bookmarks in the tree.

Questions and comments welcome. I plan to talk through the concepts behind this over the next week or two.

### CODE REVIEW

**Comment by rnewman** [comment]
And here's the non-flattened version. Reading through the commit messages will illustrate some of the edge cases that we carefully work around.

https://github.com/mozilla/firefox-ios/compare/rnewman/bm-merge-review?expand=1

**Comment by sleroux** [comment]
Still going through this but I ran it and didn't see my Bookmarks come down. I had one local bookmark, signed into FxA, synced, but no bookmarks came down from the server. I saw this warning in the console though:

2016-02-25 14:34:44.068 [Warning] [ThreeWayTreeMerger.swift:994] produceMergedTree() > Remote bookmarks not fully rooted when overlayed on mirror. Partial read or write in buffer?

**Comment by rnewman** [comment]
@sleroux: ooh, interesting. Are you able to send me your browser.db? (Feel free to drop your history…)

**Comment by rnewman** [comment]
Superseded by #1581, which adds some follow-up work and rebases on top of master.

**Pull request closed without merging**
