### PR TITLE
Include Dashlane Extension

### PR DESCRIPTION
**Pull request by irew**

### CODE REVIEW

**Comment by st3fan** [comment]
Created a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1275318

**Comment by irew** [comment]
@st3fan @jhugman going to revisit this, will close for now.

**Comment by st3fan** [comment]
@irew what was wrong with the original patch? Did that not do the trick?

**Comment by irew** [comment]
@st3fan it didn't, will try to tackle this one this week.

**Comment by garvankeeley** [comment]
Is there any plans for more work on this? What was the problem with the PR?

**Comment by irew** [comment]
This PR doesn’t actually fix the issue.

We do plan to work on it, but just have not had the time yet.


On 5 Jul 2016, at 18:55, Garvan Keeley <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any plans for more work on this? What was the problem with the PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/mozilla/firefox-ios/pull/1640#issuecomment-230536807>, or mute the thread<https://github.com/notifications/unsubscribe/AILlGUytR1qfn9U2v5-wMtLetD6ixVnVks5qSoyLgaJpZM4HzKv7>.

____________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
____________________________________________________________


____________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
____________________________________________________________

**Pull request closed without merging**
