### PR TITLE
Searchplugins l10n update

### PR DESCRIPTION
**Pull request by splewako**
Update serach engines list for pl as in [bug 1195784](https://bugzilla.mozilla.org/show_bug.cgi?id=1195784) and Wikipedia icons for all reamining locales as in en and [bug 1193421](https://bugzilla.mozilla.org/show_bug.cgi?id=1193421).

### CODE REVIEW

**Comment by rnewman** [comment]
Wikipedia assets: https://github.com/mozilla/firefox-ios/commit/66f640af7288cfe2a792bbb44d1f9617459cd27f

**Comment by rnewman** [comment]
Search engine change: 50df012

**Comment by rnewman** [comment]
Thanks for the PR!

**Comment by splewako** [comment]
Thank you for landing this so fast.

**Pull request closed without merging**
