### PR TITLE
Bug 1234835 - (WIP) WebViewPanel Prototyping

### PR DESCRIPTION
**Pull request by sleroux**
This branch includes a new Top Sites Panel that displays a WKWebView. To show this panel the debug settings bundle has a new option that allows you to input any URL. When a URL is set, the web view panel replaces the Top Sites Panel and loads the given URL. On top of loading the URL a data API is exposed to the web page to allow the page to access native parts of the app such as history, bookmarks, and top sites. This should only be used in prototyping and not used for general web pages in the browser.

Currently only history items are exposed through the mozAPI.

### CODE REVIEW

**Comment by sleroux** [comment]
@darrinhenein Here's the first pass at getting the web panel stuff working. Right now only history items are exposed. Load up http://people.mozilla.org/~sleroux/panel.html to see a super simple example of this.

**Comment by ncalexan** [comment]
@sleroux, @darrinhenein -- first, this is awesome.  I'm assuming this is
intended to let us prototype quickly, and I support that.

If we do build more functionality around this, I'd like to plant two
seeds.  The first is that the FxA + Sync settings should live in such a
live panel.  (On Desktop, they do.  On Android, they don't for technical
reasons only.)

The second is that Desktop has built an abstraction for message passing
between "known, certified endpoints" (like accounts.firefox.com) and
browser chrome.  It's called WebChannels:
https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/WebChannel.jsm.
It would be nice if we were "wire protocol identical" so that things built
for Desktop have a hope of working on iOS.

Yay!

**Comment by sleroux** [comment]
Thanks for the feedback @ncalexan!

For the first point regarding the FxA and Sync settings, we can definitely consolidate the existing FxAContentViewController and a web-based panel into the same ViewController. This will also enable us to have a foundation for other web-based screens we might want to add in the future. 

Combining the second point, this web-based controller would also be able to implement the WebChannel.jsm wire protocol which would allow us to abstract the API needed for any page we want to render. For example, I notice that in the FxAContentViewController there is some JS <-> Swift code for handling account callbacks. Could this be implemented using WebChannels?

Lastly I feel like this is related to addon support in the future for iOS. CC'ing @jhugman for input!

**Comment by ncalexan** [comment]
On Wed, Dec 23, 2015 at 1:07 PM, Stephan Leroux <notifications@github.com>
wrote:

> Thanks for the feedback @ncalexan <https://github.com/ncalexan>!
>
> For the first point regarding the FxA and Sync settings, we can definitely
> consolidate the existing FxAContentViewController and a web-based panel
> into the same ViewController. This will also enable us to have a foundation
> for other web-based screens we might want to add in the future.
>
Excellent.  Just wanted to seed this -- Accounts is a little special right
now but shouldn't be that way forever.

> Combining the second point, this web-based controller would also be able
> to implement the WebChannel.jsm wire protocol which would allow us to
> abstract the API needed for any page we want to render. For example, I
> notice that in the FxAContentViewController there is some JS <-> Swift code
> for handling account callbacks. Could this be implemented using WebChannels?
>
Yes, we'd like to implement the JS <-> Swift part using WebChannels
eventually.  (fx_ios_v2 protocol will be over WebChannels.)  And in fact
both Android and Desktop now use WebChannels.

**Pull request closed without merging**
