### PR TITLE
Bug 1279455 - only display changes in sync state in the status bar

### PR DESCRIPTION
**Pull request by fluffyemily**
https://bugzilla.mozilla.org/show_bug.cgi?id=1279455

### CODE REVIEW

**Comment by sleroux** [comment]
This is still showing me the bookmark sync warning message notification everytime since the defer call is always showing the notification regardless of what `syncMessageForNotification` returns [1].

[1] https://github.com/mozilla/firefox-ios/pull/1910/files#diff-1806bc807450a894013313c45975a48cR248

**Comment by fluffyemily** [comment]
conveniently, your patch for https://github.com/mozilla/firefox-ios/pull/1907 should resolve that issue

**Comment by sleroux** [comment]
Thats.. what I thought! 😁 Sounds good.

**Comment by fluffyemily** [comment]
We should make sure that #1907 lands first, probably

**Comment by sleroux** [comment]
Landed! https://github.com/mozilla/firefox-ios/pull/1907

**Comment by fluffyemily** [comment]
awesome. I'll rebase and you can retest if you want. Otherwise, just r+ me ;)

**Pull request merged**
