### PR TITLE
Bug 1169075 - Highlight elements when tapped

### PR DESCRIPTION
**Pull request by thebnich**
This has taken a lot of tweaking to get working properly, and there are still a few random issues I've noticed:

* The page's default highlighting style isn't applied.
 * Example: [advocacy.mozilla.org](http://advocacy.mozilla.org). Touching the buttons would normally change to a blue color.
 * Another example: [yahoo.com](https://search.yahoo.com/mobile/s?p=test&fr=yfp-hrmob-900&fr2=p%3Afp%2Cm%3Asb&.tsrc=yfp-hrmob-900), when touching links in a result page. Normally, the links turn to a lighter blue color when highlighting.
* The highlight is sometimes "off". For example, on [foxnews.com](http://www.foxnews.com), the highlight for all of the links doesn't fully extend to the bottom/right sides. My guess is that `getClientRects()` is slightly off for some reason these cases -- not sure if there's anything we can do about it.

### CODE REVIEW

**Comment by thebnich** [comment]
@wesj might also want to take a look since I think you've worked on similar stuff on the Android side. Curious if there are any solutions to the issues mentioned above...

**Comment by wesj** [comment]
> The highlight is sometimes "off".

HTML-Transforms sometimes aren't reflected in these things, but I don't see any on FoxNews.

**Comment by thebnich** [comment]
> Injecting content into the DOM feels pretty dangerous to me. Why wouldn't we use native UI for this?

By "dangerous", do you mean security-wise for the browser, or just breaking page compat? I'm not worried about the former in this case since the `div`s we're injecting are just a visual cue that we don't interact with. I am a bit concerned about things breaking in general, though...if the page does something as simple as `window.onscroll = ...`, it will clobber our listener :-\ Though using native UI wouldn't help in that case, unless we had some way to attach the listeners natively...

> Webkit supports a -webkit-tap-highlight-color that pages can use here

Yeah, I found that property too. Unfortunately, the value was always `""` when I checked the broken cases I mentioned, so I guess those active effects are coming from somewhere else.

**Comment by thebnich** [comment]
Merged 315a6aa. Let's see what happens.

**Comment by wesj** [comment]
Webkit supports a -webkit-tap-highlight-color that pages can use here
I know I saw it in the CSS on the Mozilla site you pointed out.

**Comment by thebnich** [comment]
Hm, I see it too when I look at the CSS rules inspector for the button, but then `$0.style.webkitTapHighlightColor` returns an empty string.

**Pull request closed without merging**
