### PR TITLE
Bug 1127505 - Set APPLICATION_EXTENSION_API_ONLY = YES for extension targets.

### PR DESCRIPTION
**Pull request by rnewman**
This doesn't make the warning go away in Xcode, even though it's what the docs say…

### CODE REVIEW

**Comment by st3fan** [comment]
I think that setting needs to be in the project that generates the framework? So in `Storage/Storage.xcodeproj/project.pbxproj` ?

**Comment by rnewman** [comment]
Hmm, poorly worded docs!

**Comment by rnewman** [comment]
I think it's safe to leave that flag set for the extensions themselves, so leaving that in the commit.

**Comment by st3fan** [comment]
The extensions should already have it. I am pretty sure I fixed that a while ago because I saw the same errors.

What the flag does is set some preprocessor flag that trigger warnings when you use some specific APIs when compiling your framework code. (An extension is a framework). This is why it needs to be part of the target that builds the framework and not in the target that consumes the built framework.

**Comment by rnewman** [comment]
Yeah, the concept makes sense, which is why I was a little confused by the docs in the first place!

I noticed that Xcode kinda thought the extensions had that setting already, sometimes showing No and sometimes Yes, but after some effort it stuck, and they're new in the diff, so *shrug*. Yay Xcode.

**Comment by st3fan** [comment]
Confusion resolved. I did not get the warning for the extensions but for the dependencies:

https://github.com/mozilla/firefox-ios/search?utf8=✓&q=APPLICATION_EXTENSION_API_ONLY

Snappy and Alamofire.

**Pull request closed without merging**
