### PR TITLE
St3fan/bug1109656 location completion

### PR DESCRIPTION
**Pull request by st3fan**
This implemented a first iteration of location completion. It implements the following rules:

* If the user types `www.m` and we have a completion suggestion `http://www.mozilla.org`, the completion will be `www.mozilla.org`.
* If the user types `m` and we have a completion suggestion `http://www.mozilla.org`, the completion will be `mozilla.org`.
* If the user types `http://wwww.m` and we have a completion suggestion `http://www.mozilla.org`, the completion will be `http://www.mozilla.org`.

In all cases the completion suggestion will *also* include the actual source URL `http://www.mozilla.org` - so that we can make a difference between what is typed in the location field and what that actually resolves to.

Currently the patch includes a fixed list of mock suggestions. I will file a followup bug to hook this up to our real datasources.

The code currently does not deal with paths in URLs. This is intentional. If we require that, then I will add a followup bug to adjust the API accordingly.

### CODE REVIEW

**Comment by st3fan** [comment]
@wesj Yeah I think you are right about doing async operations. Unless we can somehow guarantee that lookups are within a certain time range. (But maybe our history API is async anyway, which means we have no choice)

Not entirely sure yet how to map async lookups to the text field yet. We may have to cancel previous lookups if keystrokes happen before a running query is finished. (How likely is that?)

**Comment by st3fan** [comment]
@wesj *Not having the caret when the completion is active seems sad. Follow up to fix?* - I've followed the visual design of completion in Safari.

**Comment by st3fan** [comment]
This needs to be rewritten with all the recent changes regarding the location field.

**Comment by thebnich** [comment]
Newer implementation in #300.

**Pull request closed without merging**
