### PR TITLE
Bug 1118046 -  Import sqlite and FMDB in place of CoreData

### PR DESCRIPTION
**Pull request by wesj**

### CODE REVIEW

**Comment by st3fan** [comment]
This is obviously work in progress. Looks good to me.

**Comment by sveinhal** [comment]
Why pull in whole third party libs into the repo? Why not use CocoaPods or git sub modules? This question obviously also relates to already existing code in the repo and not just this pull request.

**Comment by thebnich** [comment]
CocoaPods just recently added Swift support a couple weeks ago with the <a href="http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/">0.36 beta</a>. Once our libs have been updated to work with CocoaPods, I think we'll consider it.

**Comment by wesj** [comment]
This has some issues if you actually use FMDB in it (just stuff missing from the project files). I fixed them up in the next pull request, and this should be fine (since it doesn't actually use FMDB).

**Pull request merged**
