### PR TITLE
Bug 1132795 - Use Carthage for dependency management

### PR DESCRIPTION
**Pull request by thebnich**
Carthage is a dependency management that works with dynamic frameworks. The long-term goal of Carthage is to build frameworks that can be imported into the project, but there are some issues with building now. For one, several of the projects we're using (KIF, SWXMLHash, and GCDWebServer) don't have shared dynamic frameworks. Secondly, there's a copy-frameworks hack mentioned in https://github.com/Carthage/Carthage that I'd prefer to avoid.

Thankfully, Carthage has a <code>--no-build</code> option that simply pulls in the depencies without trying to build them, which is useful while Carthage is still in its infancy and the build issues are being resolved. Some discussion on <code>--no-build</code> here: https://github.com/Carthage/Carthage/issues/174

### CODE REVIEW

**Comment by thebnich** [comment]
To get a working project with these changes:
 1. <a href="https://github.com/Carthage/Carthage#installing-carthage">Install Carthage</a>.
 1. Run <code>carthage update --no-build</code>.

Some notes:
* We still have a swift-json git submodule sitting in the tree. Looks like it was unused, so removed.
* Snappy was renamed to Snap. Updated the code accordingly.
* We were importing SWXMLHash.swift directly before, and we were using some non-public APIs. Moving it to a subproject encapsulates those methods and caused build errors, so I updated the code to use the equivalent public APIs.
* I imagine this will break Travis CI. I'll leave that to @st3fan :) Note that when testing this, I had to delete the ~/Library/Developer/Xcode/DerivedData directory whenever removing a project since it stays cached in Xcode. Travis might continue to pass for the same reason.
* We'll also want to update the README. I can tack on a commit doing that before landing this, but figured I'd get some feedback on this first.

**Comment by st3fan** [comment]
I'm getting a build failure:

```
/Users/sarentz/Mozilla/firefox-ios-thebnich/Client-Bridging-Header.h:6:9: error: 'SWXMLHash/SWXMLHash.h' file not found
#import <SWXMLHash/SWXMLHash.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/sarentz/Mozilla/firefox-ios-thebnich/Client-Bridging-Header.h'
```

**Comment by st3fan** [comment]
Btw. This is awesome. Lets work through the build failures and get this going. We can also do this side by side next tuesday if that is easier. I don't want to rush it because keeping the builds working is high priority.

**Comment by st3fan** [comment]
It looks like this patch or Carthage changes the default Build Configuration for the Archive phase back to Release instead of FennecAurora.

I changed the Client scheme to change it back to AuroraNightly, but then the project does not build because the dependencies pulled in by Carthage are built using the Release build configuration while our app is using the FennecAurora one.

I solved that by simply making our dependent projects aware of the FennecAurora configuration but I don't know if that is possible with this new setup because we basically pull the dependencies in as-is and cannot make changes to those projects.

**Comment by st3fan** [comment]
Also see https://github.com/Carthage/Carthage/issues/314

**Comment by thebnich** [comment]
> I'm getting a build failure:

Did you try deleting DerivedData? Everything is working for me with a clean build.

**Pull request merged**
