### PR TITLE
Bug 1134231 - Send email feedback with app snapshot

### PR DESCRIPTION
**Pull request by sleroux**
This patch adds the ability for the user to use the snapshot function (HOME+Power Button) to take a snapshot of the running app and display an email composer form for the tester to fill out with feedback. Couple of notes:

* I'm not sure what mechanism is in place for toggling this for debug/testing/production builds but ideally it would only be enabled for testing.
* AppDelegate.swift:L95 requires an email to send the feedback to.
* MFMailComposeViewController does NOT work on iOS 8 simulators so I can't test this yet.
* The snapshot function also doesn't work on the simulator so it will need to be tested on device as well. I was able to simulate it by posting the notification in code though.

### CODE REVIEW

**Comment by st3fan** [comment]
@sleroux Just a quick note that I will review and merge this today or tomorrow. Proooobably tomorrow.

**Comment by sleroux** [comment]
No problem. I'll keep an eye out for any changes needed tonight/tomorrow.

**Comment by sleroux** [comment]
Before this PR goes into the filing bin, just a quick note that 
AppDelegate.swift:L95 still needs an email to be filled in.

**Comment by st3fan** [comment]
Yeah I'm asking our product manager to provide the email and a small piece of template text that we can put in the email  by default.

**Pull request merged**
