### PR TITLE
Bug 1168693 - Don't enable pull-to-sync for History panel unless Sync is configured

### PR DESCRIPTION
**Pull request by Johennes**

### CODE REVIEW

**Comment by rnewman** [comment]
Needs rebase and a couple of changes, but otherwise a nice minimal fix; thanks!

**Comment by Johennes** [comment]
@rnewman Thanks for the comments. I'll work your suggestions in. I probably won't manage to do so before the weekend though. Hope that's ok.

**Comment by rnewman** [comment]
Sounds good, Johennes; thanks!

**Comment by Johennes** [comment]
I rebased the commit and switched to using `profile.hasSyncableAccount()` which seems to work as expected. I also made a minor adjustment to when the refresh control's animation is ended (see my comment before this one).

**Comment by rnewman** [comment]
LGTM, Johennes!

**Comment by rnewman** [comment]
c2655c3

**Pull request closed without merging**
