### PR TITLE
Bug 1166018 - Firefox pauses system audio when launched (while not previously running)

### PR DESCRIPTION
**Pull request by sleroux**

### CODE REVIEW

**Comment by thebnich** [comment]
Hm, so audio will still pause if VoiceOver is turned on, right? Is that expected?

@dusek landed this last week for parity with Safari. I wonder if Safari pauses audio with VoiceOver enabled.

**Comment by dusek** [comment]
I am looking into what happens with Safari, but I doubt it would stop audio with (or without) VoiceOver – being able to listen to music while browsing web feels obvious.

I think the right thing would be to set something like [`AVAudioSessionCategoryAmbient`](https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/index.html#//apple_ref/doc/constant_group/Audio_Session_Categories), that would allow to mix Safari's sounds (the progress bar) with music from other apps. I will post when I learn more (I guess this weekend).

**Comment by dusek** [comment]
So Safari, as I expected, does not stop audio from external apps when its aural progress indicator is playing with VoiceOver. (But btw. it e.g. stops audio on webpages that had media content (video) - i.e. CNN article with video report, even if you don't play it.) It also plays the aural progress ticks even with silent switch on (Firefox does not play it with silent switch on). Guess I will have to look at all these issues and open a PR :-) Looks like the right thing to mimic that would instead be `AVAudioSessionCategoryPlayback` (leads to no turning off the audio progress when silent switch is on) along with the `AVAudioSessionCategoryOptionMixWithOthers` option (leads to no pausing background music from other apps).

**Comment by sleroux** [comment]
@dusek, do you want to continue working on this branch? You have a lot of good ideas on implementing this feature. Let me know and I can assign the bugzilla bug over to you :)

**Comment by dusek** [comment]
Yep, I will work on it.

**Comment by sleroux** [comment]
Awesome thanks! I'll assign the bug over to you.

**Pull request closed without merging**
