### PR TITLE
3d touch quick actions for firefox

### PR DESCRIPTION
**Pull request by sachin004**
Quick actions such as "New Tab", "New Private Tab", "Show Bookmarks", "Show reading list" are added

simulator screen shot sep 27 2015 6 39 49 pm

to run it on a simulator use https://github.com/DeskConnect/SBShortcutMenuSimulator .

Currently there are four major issues with this:
- Tab count goes wrong after some time when private tab is added through shortcut.
- When bookmarks/reading list is opened from shortcuts, home panel resets to top sites once we leave the tab and open any other tab and come back to it.
- In CrashReporterTests.swift import Client fails
- Deprecated methods in iOS 9 needs to be fixed.

I am looking for feedback and any help you guys could give me with the above four issues.

### CODE REVIEW

**Comment by sleroux** [comment]
Hey Sachin,
Sorry for the delay on feedback on this! This patch/functionality looks fantastic - we definitely want to get some 3D touch in the app. We're just finishing up our next release now so it's been a bit hectic but I'd like to review this and get feedback on it as soon as possible. In the meantime, I know our design folks have been looking into what we want to do around force touch so I'll CC them to this thread to get some of their feedback as well. Thanks for the patch!

@tecgirl @darrinhenein

**Comment by fluffyemily** [comment]
Hi @sachin004. I've just come across this patch as we start to look at adding QuickActions for Firefox for iOS. We're looking to do something slightly different to what you have done here (New Tab and New Private Tab but with dynamic options for the last 2 items). Did you want to look at bringing this patch into line with our planned design, or we can use your patch as a basis for our new work?

**Comment by sachin004** [comment]
@fluffyemily Do you have any design document for this? Could you explain a bit more about dynamic options?

**Comment by fluffyemily** [comment]
@sachin004 we actually just landed the static Quick Actions on master today. For dynamic Quick Actions, these are actions that will be added and removed according to the state of the app. They are described in the Apple 3D touch documenation here: https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/3DTouchAPIs.html#//apple_ref/doc/uid/TP40016543-CH4-SW1

We are now starting to work on the dynamic actions. Maybe you'd like to implement one of them? How about this one? https://bugzilla.mozilla.org/show_bug.cgi?id=1227108? Links to the design can be found in the bug.

**Comment by fluffyemily** [comment]
I would be happy to talk it through with you and what we are trying to do.

**Comment by sachin004** [comment]
@fluffyemily If static quick actions are already on master I can close this pull right? Sure I would like to more about dynamic actions.

**Comment by fluffyemily** [comment]
@sachin004 yup, you can close this request. If you want to talk more about what we are doing with dynamic actions, come talk to us on irc (irc.mozilla.com) in #mobile.

**Pull request closed without merging**
