### PR TITLE
Fluffyemily/bug 1205015 automated l10n screenshots

### PR DESCRIPTION
**Pull request by fluffyemily**
https://bugzilla.mozilla.org/show_bug.cgi?id=1205015

* create snapshot subgroup
* create new testing target for l10n snapshot tests
* remake marketing snapshot tests so that they work properly
* ensure test schemes can run from snapshot
* add firefox-ios-l10n to .gitignore (now it's a git repo, l10n it doesn't play nice as a submodule)

### CODE REVIEW

**Comment by sleroux** [comment]
I tried running the marketing lane but I'm getting this error:
`The scheme 'ClientUITests' has nothing configured to build for Running and has no executable specified to Run. Edit the scheme to configure the Run action.`

I think this got moved to ClientRefTests?

Also, I think we should move the marketing/l10n snapshots into their own scheme (ClientSnapshots) instead of ClientRefTests. I'm just afraid that adding them into the RefTests scheme would imply that they are tests when it's really a tool for generating snapshots of the app.

**Comment by fluffyemily** [comment]
So, what this branch should have done (and does on my local version) is get rid of `ClientUITests` entirely and replace them with `L10nSnapshotTests` and `MarketingSnapshotTests` under a new group called Snapshot. Don't know why you are still seeing `ClientUITests` as that should not be present any more and the branch on `firefox-ios-build-tools` should reference `MarketingSnapshotTests` when you run `fastlane marketing` and `L10nSnapshotTests` when you run `fastlane snapshotL10n`

**Comment by fluffyemily** [comment]
Can you check your version of `fastlane/Snapfile` and see what the `scheme` property is set to?

**Comment by sleroux** [comment]
Not sure if its just my copy but I tried doing the following after this was merged in:

1. Modifed fastlane/Fastlane to point to `fluffyemily/Bug-1205015-automated-l10n-screenshots`
2. Commited changes
3. `git clean -fx` to clean out any previous Carthage/ stuff (similar to re-cloning)
4. `fastlane marketing'

I get get the following error:

`The scheme 'MarketingUITests' has nothing configured to build for Running and has no executable specified to Run. Edit the scheme to configure the Run action.`

I took a look at the schemes for the Marketing/L10N snapshots and they don't seem to have an executable configured https://www.dropbox.com/s/q1e2esds6150kcy/Screenshot%202016-01-25%2009.16.53.png?dl=0&preview=Screenshot+2016-01-25+09.16.53.png/.

After hooking up Client as the executable I was able to run the Marketing snapshots but the snapshot tests failed for the default 'de', 'en-US', 'it-IT' locales:

```
Test Suite MarketingUITests.xctest started
MarketingSnapshotTests
✗ testTakeMarketingScreenshots, UI Testing Failure - No matches found for Button


MarketingUITests.MarketingSnapshotTests
testTakeMarketingScreenshots, UI Testing Failure - No matches found for Button
/Users/sleroux/development/firefox-ios/MarketingUITests/MarketingUITests.swift:61

        // go to synced tabs home screen
        app.buttons.elementBoundByIndex(4).tap()
        snapshot("03SyncedTabs")
 Executed 1 test, with 1 failure (0 unexpected) in 8.477 (8.480) seconds
```
I didn't run the localize string so I could imagine the it-IT and de ones failing but not sure why the en-US one would be.

For the L10N run through, I was able to run it right away since the executable was already configured but it only ran the example test so there were no snapshots actually taken. Is this expected?

```
L10nSnapshotTests
[09:26:32]: ▸ ✓ testExample (3.480 seconds)
[09:26:32]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 3.480 (3.483) seconds
[09:26:32]: ▸
[09:26:32]: Collecting screenshots...
[09:26:33]: Found 0 screenshots...
```

The snapshots.html file did open afterwards though.

**Comment by fluffyemily** [comment]
yeah, ignore the marketing snapshot tests for now. They are always
breaking. I'll fix those. I'll also fix the missing Client executable on
the marketing snapshot tests. This PR is far more about getting us to a
point where we can write l10n tests. I'll raise a new bug re: the failing
marketing tests.

**Pull request merged**
