### PR TITLE
Bug 1210185 - "Open In Private Browser" string has wrong capitalization

### PR DESCRIPTION
**Pull request by aaronraimist**

### CODE REVIEW

**Comment by rnewman** [comment]
This will lose some existing translations, so we can't land this yet.

**Comment by sleroux** [comment]
> will lose some existing translations, so we can't land this yet.

@rnewman Was this comment from our inability to translate the new string in time for a release? Can we merge this and have it picked up in the next localization cycle?

**Comment by rnewman** [comment]
Yes, @sleroux, exactly that. It can follow the usual landing process. (note that you'll want to rebase away all of those merge commits)

**Comment by sleroux** [comment]
I've rebased this work and landed the changes on this commit https://github.com/mozilla/firefox-ios/commit/cf00c19f86e6b0bc91301d52320618d7b16c981f.

Thanks Aaron and sorry for the delay!

**Pull request closed without merging**
