### PR TITLE
Bug 1158216 - Sync passwords

### PR DESCRIPTION
**Pull request by rnewman**
I've left these commits in story form for now, because I think the individual steps will make sense to @ncalexan. Preliminary review, please!

I want to write some more integrationey tests via a fake storage client, but I might settle for enough manual testing.

Hook-up work to follow.

### CODE REVIEW

**Comment by rnewman** [comment]
lttm

**Comment by rnewman** [comment]
Reviewed by @st3fan. Still waiting on @ncalexan.

**Comment by ncalexan** [comment]
Comments on the commits.  This was surprisingly easy to read -- thanks for the story order.

**Comment by rnewman** [comment]
Merged flat and I'll land as part of #660. Thanks for the reviews!

**Pull request closed without merging**
